# DSC summary & query

This page displays contents of database `dsc_result.db` generated by [this DSC](dsc_result.html). There are two types of tables in the database:

* **pipeline** tables: describes how module instances are connected to a pipeline, via module instance ID.
* **module** tables: parameters and dependencies of module instances.

In [1]:
import pickle
data = pickle.load(open("dsc_result/dsc_result.db", 'rb'))

## Pipelines

### mse

**normal -> mean -> mse**

In [2]:
%preview -n data['pipeline_mse']['normal+mean+mse'] --limit -1

>>> data['pipeline_mse']['normal+mean+mse']:

,normal,mean,mse
0,1,11,21
1,2,12,22
2,3,13,23
3,4,14,24
4,5,15,25
5,6,16,26
6,7,17,27
7,8,18,28
8,9,19,29
9,10,20,30

**normal -> median -> mse**

In [3]:
%preview -n data['pipeline_mse']['normal+median+mse'] --limit -1

>>> data['pipeline_mse']['normal+median+mse']:

,normal,median,mse
0,1,31,41
1,2,32,42
2,3,33,43
3,4,34,44
4,5,35,45
5,6,36,46
6,7,37,47
7,8,38,48
8,9,39,49
9,10,40,50

**t -> mean -> mse**

In [4]:
%preview -n data['pipeline_mse']['t+mean+mse'] --limit -1

>>> data['pipeline_mse']['t+mean+mse']:

,t,mean,mse
0,51,61,71
1,52,62,72
2,53,63,73
3,54,64,74
4,55,65,75
5,56,66,76
6,57,67,77
7,58,68,78
8,59,69,79
9,60,70,80

**t -> median -> mse**

In [5]:
%preview -n data['pipeline_mse']['t+median+mse'] --limit -1

>>> data['pipeline_mse']['t+median+mse']:

,t,median,mse
0,51,81,91
1,52,82,92
2,53,83,93
3,54,84,94
4,55,85,95
5,56,86,96
6,57,87,97
7,58,88,98
8,59,89,99
9,60,90,100

## Modules

### module `normal`

In [6]:
%preview -n data['normal'] --limit -1

>>> data['normal']:

,ID,PARENT,FILE,seed,true_mean,n
0,1,-9,normal_1,1,0,1000
1,2,-9,normal_2,1,1,1000
2,3,-9,normal_3,2,0,1000
3,4,-9,normal_4,2,1,1000
4,5,-9,normal_5,3,0,1000
5,6,-9,normal_6,3,1,1000
6,7,-9,normal_7,4,0,1000
7,8,-9,normal_8,4,1,1000
8,9,-9,normal_9,5,0,1000
9,10,-9,normal_10,5,1,1000

### module `mean`

In [7]:
%preview -n data['mean'] --limit -1

>>> data['mean']:

,ID,PARENT,FILE
0,11,1,normal_1_mean_1
1,12,2,normal_2_mean_1
2,13,3,normal_3_mean_1
3,14,4,normal_4_mean_1
4,15,5,normal_5_mean_1
5,16,6,normal_6_mean_1
6,17,7,normal_7_mean_1
7,18,8,normal_8_mean_1
8,19,9,normal_9_mean_1
9,20,10,normal_10_mean_1
10,61,51,t_1_mean_1
11,62,52,t_2_mean_1
12,63,53,t_3_mean_1
13,64,54,t_4_mean_1
14,65,55,t_5_mean_1
15,66,56,t_6_mean_1
16,67,57,t_7_mean_1
17,68,58,t_8_mean_1
18,69,59,t_9_mean_1
19,70,60,t_10_mean_1

### module `mse`

In [8]:
%preview -n data['mse'] --limit -1

>>> data['mse']:

,ID,PARENT,FILE
0,21,11,normal_1_mean_1_mse_1
1,22,12,normal_2_mean_1_mse_1
2,23,13,normal_3_mean_1_mse_1
3,24,14,normal_4_mean_1_mse_1
4,25,15,normal_5_mean_1_mse_1
5,26,16,normal_6_mean_1_mse_1
6,27,17,normal_7_mean_1_mse_1
7,28,18,normal_8_mean_1_mse_1
8,29,19,normal_9_mean_1_mse_1
9,30,20,normal_10_mean_1_mse_1
10,41,31,normal_1_median_1_mse_1
11,42,32,normal_2_median_1_mse_1
12,43,33,normal_3_median_1_mse_1
13,44,34,normal_4_median_1_mse_1
14,45,35,normal_5_median_1_mse_1
15,46,36,normal_6_median_1_mse_1
16,47,37,normal_7_median_1_mse_1
17,48,38,normal_8_median_1_mse_1
18,49,39,normal_9_median_1_mse_1
19,50,40,normal_10_median_1_mse_1
20,71,61,t_1_mean_1_mse_1
21,72,62,t_2_mean_1_mse_1
22,73,63,t_3_mean_1_mse_1
23,74,64,t_4_mean_1_mse_1
24,75,65,t_5_mean_1_mse_1
25,76,66,t_6_mean_1_mse_1
26,77,67,t_7_mean_1_mse_1
27,78,68,t_8_mean_1_mse_1
28,79,69,t_9_mean_1_mse_1
29,80,70,t_10_mean_1_mse_1
30,91,81,t_1_median_1_mse_1
31,92,82,t_2_median_1_mse_1
32,93,83,t_3_median_1_mse_1
33,94,84,t_4_median_1_mse_1
34,95,85,t_5_median_1_mse_1
35,96,86,t_6_median_1_mse_1
36,97,87,t_7_median_1_mse_1
37,98,88,t_8_median_1_mse_1
38,99,89,t_9_median_1_mse_1
39,100,90,t_10_median_1_mse_1

### module `median`

In [9]:
%preview -n data['median'] --limit -1

>>> data['median']:

,ID,PARENT,FILE
0,31,1,normal_1_median_1
1,32,2,normal_2_median_1
2,33,3,normal_3_median_1
3,34,4,normal_4_median_1
4,35,5,normal_5_median_1
5,36,6,normal_6_median_1
6,37,7,normal_7_median_1
7,38,8,normal_8_median_1
8,39,9,normal_9_median_1
9,40,10,normal_10_median_1
10,81,51,t_1_median_1
11,82,52,t_2_median_1
12,83,53,t_3_median_1
13,84,54,t_4_median_1
14,85,55,t_5_median_1
15,86,56,t_6_median_1
16,87,57,t_7_median_1
17,88,58,t_8_median_1
18,89,59,t_9_median_1
19,90,60,t_10_median_1

### module `t`

In [10]:
%preview -n data['t'] --limit -1

>>> data['t']:

,ID,PARENT,FILE,seed,true_mean,n
0,51,-9,t_1,1,0,1000
1,52,-9,t_2,1,1,1000
2,53,-9,t_3,2,0,1000
3,54,-9,t_4,2,1,1000
4,55,-9,t_5,3,0,1000
5,56,-9,t_6,3,1,1000
6,57,-9,t_7,4,0,1000
7,58,-9,t_8,4,1,1000
8,59,-9,t_9,5,0,1000
9,60,-9,t_10,5,1,1000